name: Build and deploy Python app to Azure Web App - mira-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest   # ✅ Fixed typo
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r api/requirements.txt

      - name: Zip only contents of api/
        run: |
          cd api
          zip -r ../release.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_22C67F22BDC94647A593B12A2B07E602 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C6BAE1B8E65D4389A02F11AA3E115BBB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_858418EF476441AE867DEE2C03E79B2E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'mira-backend'
          slot-name: 'Production'
          package: release.zip
          type: runFromPackage  # ✅ Ensures smoother Python ZIP deploy
